# Generated by Django 6.0.6 on 2026-06-13 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('borrowings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(condition=models.Q(('expected_return_date__gt', models.F('borrow_date'))), name='expected_return_date_after_borrow_date'),
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(condition=models.Q(('actual_return_date__isnull', True), ('actual_return_date__gte', models.F('borrow_date')), _connector='OR'), name='actual_return_date_after_or_equal_borrow_date'),
        ),
    ]
